### ISSUE TITLE
Не работает оплата через Тинькофф банк

### ISSUE THREAD

**Issue by XAHTEP26** [yoomoney/cms-drupal7#44]
При выборе оплаты через Тинькофф банк происходит ошибка:
`Error: Class 'YandexCheckout\Model\PaymentData\PaymentDataTinkoffBank' not found в функции YandexCheckout\Model\PaymentData\PaymentDataFactory->factory() (строка 64 в файле \sites\all\modules\yandex-money-cms-v2-drupal-master\yandex-checkout-sdk-php\lib\Model\PaymentData\PaymentDataFactory.php).`

Это явно происходит потому что не хватает файла PaymentDataTinkoffBank.php из библиотеки yandex-checkout-sdk-php. Хотя в репозитории этой библиотеки [такой файл есть](https://github.com/yandex-money/yandex-checkout-sdk-php/blob/master/lib/Model/PaymentData/PaymentDataTinkoffBank.php).

**Comment by ostulov** [comment]
Ошибка была исправлена ранее.
