### ISSUE TITLE
Не меняется статус заказа на completed

### ISSUE THREAD

**Issue by dgastudio** [yoomoney/cms-drupal7#46]
Добрый день
по факту успешной оплаты, я возвращаюсь на сайт, но, статус заказа не меняется на completed. Также, не создается новый юзер (не срабатывает checkout_completed).

**Comment by ostulov** [comment]
Добрый день!

Статус заказа меняется благодаря получению уведомления от Яндекс.Кассы.
Скопируйте адрес из настроек модуля и установите его в личном кабинете Яндекс.Кассы (https://kassa.yandex.ru/my/shop-settings).

**Comment by dgastudio** [comment]
статус заказа поменялся (я в правилах менял)
но вот юзер не создался потому что commerce_checkout_complete не запускается

после вот такого фикса, все заработало
https://monosnap.com/file/N5FL8MGU7p8BvgmTaU616NcwxWsl1m

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание, рассмотрим добавление commerce_checkout_complete

**Comment by ostulov** [comment]
Исправлено в v2.0.1
