### ISSUE TITLE
После оплаты не изменяется статус заказа

### ISSUE THREAD

**Issue by lagodinm** [yoomoney/cms-drupal7#51]
После успешной оплаты не срабатывает типовое правило "When an order is first paid in full"
В иных платежных шлюзах правило отрабатывает корректно.
Такая же проблема у тинькоф была описано здесь http://dru.io/question/9610
Также не отрабатывают правило "Окончание процесса оформления"

**Comment by ostulov** [comment]
Добрый день!

Благодарю за информацию, рассмотрим возможность добавления обработки правил.
При наличии проблемы со сменой статуса заказа проверьте, что адрес отправки уведомления об успешной оплаты установлен правильно.

**Comment by lagodinm** [comment]
В интерфейсе юкассы есть такая настройка [https://ibb.co/0fs0VPP](url)
В настройках модуля такая настройка [https://ibb.co/Pw0gXbZ](url)
Подскажите, что может быть неправильно в адресе, если настройки из вашей "коробки"?

**Comment by ostulov** [comment]
Иногда адреса могут различаться.
Нажмите на кнопку "Задать вручную" и установите именно тот адрес, который отображается у Вас в настройках на сайте.

**Comment by lagodinm** [comment]
Изменил адрес в настройках кабинета кассы вручную, как в модуле. Теперь все работает как полагается, даже правило When an order is first paid in full отрабатывает. Спасибо.
Ни за что бы не догадался, что надо вручную изменить адрес, много времени потратил...
